### ISSUE TITLE
Data as text

### ISSUE THREAD

**Issue by Kephalos5** [mold/explr#13]
is there any way we can get the data for our countries as well as scrobbles and artists of those countries as pure text?
I would like to put it into pie charts and other things.

**Comment by mold** [comment]
@Kephalos5 Better late than never, there's now an export button that downloads a csv with artists and scrobbles per country 😁

**Comment by Kephalos5** [comment]
> @Kephalos5 Better late than never, there's now an export button that downloads a csv with artists and scrobbles per country 😁

Wow, thanks. Only just saw this there.
