### ISSUE TITLE
Artist Location Tags Don't Update Without Clearing Cache

### ISSUE THREAD

**Issue by pmcdonough8133** [mold/explr#24]
Not necessarily an issue depending on view but can be a frustrating feature that many users might not be aware of but artist tags do not properly update without clearing cache.

What I mean by this is that if you listen to a brand new artist that is not properly tagged yet (or any artist missing location tags), it will appear in the bottom left as artists that are missing location data.  If you click those artists, tag them, wait 1 - 3 days, they will still never move from that list to their tagged country unless you clear your cache.

If you're on chrome, use this to easily find and clear cache for just the explr site:
[chrome://settings/siteData?searchSubpage=mold.github.io](chrome://settings/siteData?searchSubpage=mold.github.io)

**Comment by mold** [comment]
Thanks for the feedback! I guess the easiest solution would be to add a button to manually clear the cache. Will take a look when I get the time.

**Comment by mold** [comment]
@pmcdonough8133 I've added a button to clear the cache and reload, please see if it helps!

**Comment by pmcdonough8133** [comment]
That fixed it! Thanks a bunch

**Comment by mold** [comment]
😚
