### ISSUE TITLE
Storage exception on large profiles

### ISSUE THREAD

**Issue by mikemanger** [mold/explr#4]
[My profile](https://www.last.fm/user/MikeManger) has a reasonably large number of artists (12000) which seems to be about the limit of Google Chrome's storage limit (which I think is 10MB):

> Uncaught DOMException: Failed to set the 'countryCountObj' property on 'Storage': Setting the value of 'countryCountObj' exceeded the quota.

Storing the data in a less verbose way will help (one hack I found was removing the image meta data in `countryCountObj` - see c91c8e29a6fa4), but catching the error and displaying a prompt is probably the way to go.

**Comment by mold** [comment]
Yo Mike! Better late than never - I just pushed a change that could solve this, replacing localStorage with local**F**orage, which uses IndexedDB or AsyncStorage or whatever is best. It should give you some extra MB's to work with. Please try it out!

**Comment by mold** [comment]
Dude, you did it. 210/210!

![image](https://user-images.githubusercontent.com/1492711/72878314-01a0e180-3cfb-11ea-867e-2b737aa3a640.png)

**Comment by mikemanger** [comment]
Oh wow, big kudos for looking at this! It is loading fine now and also the cache seems to now work, which is a bonus. localForage looks like a useful tool.

And yes my goal for 2019 was to tick off every country. :100:
